# Numpy

In [1]:
import numpy as np

In [4]:
# ndarray
v = np.array([1, 2, 3])
v

array([1, 2, 3])

In [6]:
type(v)

numpy.ndarray

In [7]:
v.dtype

dtype('int64')

In [8]:
v.size

3

In [5]:
u = np.array([-1, 0, 1])
u + v

array([0, 2, 4])

In [6]:
3 * u

array([-3,  0,  3])

In [7]:
# sucin pozlozkach
u * v

array([-1,  0,  3])

In [8]:
# skalarny sucin
u@v

2

In [9]:
A = np.array([[1, 2], [0, 1], [-1 ,1]])
A

array([[ 1,  2],
       [ 0,  1],
       [-1,  1]])

In [10]:
A.shape

(3, 2)

In [11]:
A+A

array([[ 2,  4],
       [ 0,  2],
       [-2,  2]])

In [12]:
10*A

array([[ 10,  20],
       [  0,  10],
       [-10,  10]])

In [13]:
A*A

array([[1, 4],
       [0, 1],
       [1, 1]])

In [14]:
# maticove nasobenie
A@A

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)

In [15]:
# transponovana matica
A.transpose()

array([[ 1,  0, -1],
       [ 2,  1,  1]])

In [16]:
A@A.transpose()

array([[5, 2, 1],
       [2, 1, 1],
       [1, 1, 2]])

In [17]:
# druhy prvok vektora
v[1]

2

In [18]:
# prvok matice v druhom riadku v prvom stlpci
A[1,0]

0

In [19]:
# treti riadok matice
A[2]

array([-1,  1])

In [21]:
# druhy stlpec matice
A[:,1]

array([2, 1, 1])

In [26]:
# specialne polia ones, zeros, eye
j = np.ones(7, 'int')
j

array([1, 1, 1, 1, 1, 1, 1])

In [27]:
j.dtype

dtype('int64')

In [29]:
J = np.ones((2, 3), 'int')
J

array([[1, 1, 1],
       [1, 1, 1]])

In [35]:
E = np.eye(5, k=-1, dtype='int')
E

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0]])

In [14]:
# vygenerovanie pola s nahodnymi hodnotami
from numpy import random as nr
nr.rand(5)

array([0.03689834, 0.39142135, 0.67400261, 0.87548223, 0.81500986])

In [38]:
M = nr.rand(3,4)
M

array([[0.00646231, 0.78624313, 0.24077458, 0.05970527],
       [0.49605019, 0.04121427, 0.93180335, 0.41949672],
       [0.76282058, 0.73601865, 0.0524291 , 0.01340895]])

In [42]:
# 10 pokusov hodu kockou
nr.randint(1,7,10)

array([5, 1, 1, 6, 3, 4, 3, 5, 6, 2])

In [43]:
# Maskovanie
M

array([[0.00646231, 0.78624313, 0.24077458, 0.05970527],
       [0.49605019, 0.04121427, 0.93180335, 0.41949672],
       [0.76282058, 0.73601865, 0.0524291 , 0.01340895]])

In [44]:
M < 0.5

array([[ True, False,  True,  True],
       [ True,  True, False,  True],
       [False, False,  True,  True]])

In [45]:
M[M<0.5] = 0
M

array([[0.        , 0.78624313, 0.        , 0.        ],
       [0.        , 0.        , 0.93180335, 0.        ],
       [0.76282058, 0.73601865, 0.        , 0.        ]])

### Riesenie sustavy rovnic
x+y+z = 4<br>
x+2y+4z=12<br>
2x-3y-z=4

In [17]:
A = np.array([[1, 1, 1], [1, 2, 4], [2, -3, -1]])
A

array([[ 1,  1,  1],
       [ 1,  2,  4],
       [ 2, -3, -1]])

In [12]:
b = np.array([4,12,4])
b

array([ 4, 12,  4])

In [13]:
import numpy.linalg as nl

In [14]:
x = nl.solve(A,b)
x

array([ 2., -1.,  3.])

In [15]:
# Skuska spravnosti
A@x==b

array([False,  True, False])

In [16]:
# aka velka je chyba?
A@x-b

array([-4.4408921e-16,  0.0000000e+00, -4.4408921e-16])

## Polynomy
$p_5 = x^5-3x^2+7$<br>
$p_2 = x^2-2x+1$

In [2]:
p5 = np.array([1,0,0,-3,0,7],'int')
p2 = np.array([1,-2,1],'int')

In [3]:
# nasobenie
np.polymul(p5,p2)

array([  1,  -2,   1,  -3,   6,   4, -14,   7])

$p_5.p_2=x^7-2x^6+x^5-3x^4+6x^3+4x^2-14x+7 $

In [4]:
# delenie
np.polydiv(p5,p2)

(array([1., 2., 3., 1.]), array([-1.,  6.]))

$\displaystyle \frac{p5}{p2}=x^3+2x^2+3x+1+\frac{-x+6}{x^2-2x+1}$

In [5]:
# korene polynomu
np.roots(p5)

array([ 1.27715317+0.59449393j,  1.27715317-0.59449393j,
       -0.67176533+1.56906173j, -0.67176533-1.56906173j,
       -1.21077568+0.j        ])

### Nacitanie a zapis pola zo/do suboru

In [8]:
M = np.arange(1, 101)
M = M.reshape(10,10)
M

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [11]:
# Zapisat maticu M do textoveho suboru
np.savetxt("M.txt", M, fmt='%i')

In [13]:
# Nacitenie matice z textoveho suboru
W = np.loadtxt("M.txt")

In [15]:
Q = nr.rand(1000,1000)

In [16]:
# Zapisat do binarneho suboru (kolko to trva)
%time np.save('Q', Q)

CPU times: user 0 ns, sys: 19.1 ms, total: 19.1 ms
Wall time: 18 ms


In [17]:
# kolko trva zapis do textoveho suboru
%time np.savetxt('Q.txt', Q)

CPU times: user 948 ms, sys: 32.5 ms, total: 980 ms
Wall time: 1.13 s


In [18]:
# porovnanie velkost suborov
!ls -l Q*

-rw-r--r-- 1 dragan2 studenti  8000128 Nov  2 09:53 Q.npy
-rw-r--r-- 1 dragan2 studenti 25000000 Nov  2 09:54 Q.txt


In [19]:
# porovname nacitanie
%time q = np.load('Q.npy')

CPU times: user 3.88 ms, sys: 8.02 ms, total: 11.9 ms
Wall time: 10.8 ms


In [21]:
%time qq = np.loadtxt('Q.txt')

CPU times: user 533 ms, sys: 14.1 ms, total: 547 ms
Wall time: 546 ms


### Largest Product in a Grid
<p>In the $20 \times 20$ grid below, four numbers along a diagonal line have been marked in red.</p>
<p class="monospace center">
08 02 22 97 38 15 00 40 00 75 04 05 07 78 52 12 50 77 91 08<br>
49 49 99 40 17 81 18 57 60 87 17 40 98 43 69 48 04 56 62 00<br>
81 49 31 73 55 79 14 29 93 71 40 67 53 88 30 03 49 13 36 65<br>
52 70 95 23 04 60 11 42 69 24 68 56 01 32 56 71 37 02 36 91<br>
22 31 16 71 51 67 63 89 41 92 36 54 22 40 40 28 66 33 13 80<br>
24 47 32 60 99 03 45 02 44 75 33 53 78 36 84 20 35 17 12 50<br>
32 98 81 28 64 23 67 10 <span class="red"><b>26</b></span> 38 40 67 59 54 70 66 18 38 64 70<br>
67 26 20 68 02 62 12 20 95 <span class="red"><b>63</b></span> 94 39 63 08 40 91 66 49 94 21<br>
24 55 58 05 66 73 99 26 97 17 <span class="red"><b>78</b></span> 78 96 83 14 88 34 89 63 72<br>
21 36 23 09 75 00 76 44 20 45 35 <span class="red"><b>14</b></span> 00 61 33 97 34 31 33 95<br>
78 17 53 28 22 75 31 67 15 94 03 80 04 62 16 14 09 53 56 92<br>
16 39 05 42 96 35 31 47 55 58 88 24 00 17 54 24 36 29 85 57<br>
86 56 00 48 35 71 89 07 05 44 44 37 44 60 21 58 51 54 17 58<br>
19 80 81 68 05 94 47 69 28 73 92 13 86 52 17 77 04 89 55 40<br>
04 52 08 83 97 35 99 16 07 97 57 32 16 26 26 79 33 27 98 66<br>
88 36 68 87 57 62 20 72 03 46 33 67 46 55 12 32 63 93 53 69<br>
04 42 16 73 38 25 39 11 24 94 72 18 08 46 29 32 40 62 76 36<br>
20 69 36 41 72 30 23 88 34 62 99 69 82 67 59 85 74 04 36 16<br>
20 73 35 29 78 31 90 01 74 31 49 71 48 86 81 16 23 57 05 54<br>
01 70 54 71 83 51 54 69 16 92 33 48 61 43 52 01 89 19 67 48<br></p>
<p>The product of these numbers is $26 \times 63 \times 78 \times 14 = 1788696$.</p>
<p>What is the greatest product of four adjacent numbers in the same direction (up, down, left, right, or diagonally) in the $20 \times 20$ grid?</p>


In [76]:
P = np.loadtxt('P11.txt')
stvorice = []
cyklus = 0
najvacsie = 0
# riadky
for i in range(len(P)):
    riadok = P[i]
    for j in range(len(riadok-3)):
        stvorica = riadok[j:j+4]
        vynasobene = np.prod(stvorica)
        print(vynasobene)
        print(najvacsie)
        if vynasobene > najvacsie:
            najvacsie = vynasobene
# treba to urobit pomocou generatorov    

34144.0
0
162184.0
34144.0
1216380.0
162184.0
0.0
1216380.0
0.0
1216380.0
0.0
1216380.0
0.0
1216380.0
0.0
1216380.0
0.0
1216380.0
10500.0
1216380.0
10920.0
1216380.0
141960.0
1216380.0
340704.0
1216380.0
2433600.0
1216380.0
2402400.0
2433600.0
4204200.0
2433600.0
2802800.0
4204200.0
56056.0
4204200.0
728.0
4204200.0
8.0
4204200.0
9507960.0
4204200.0
3298680.0
9507960.0
5452920.0
9507960.0
991440.0
9507960.0
1412802.0
9507960.0
4986360.0
9507960.0
5355720.0
9507960.0
5058180.0
9507960.0
3549600.0
9507960.0
5797680.0
9507960.0
2865520.0
9507960.0
11630640.0
9507960.0
13956768.0
11630640.0
569664.0
13956768.0
741888.0
13956768.0
666624.0
13956768.0
0.0
13956768.0
0.0
13956768.0
0.0
13956768.0
0.0
13956768.0
8981847.0
13956768.0
6098785.0
13956768.0
9832735.0
13956768.0
4440590.0
13956768.0
1764070.0
13956768.0
2982882.0
13956768.0
2680818.0
13956768.0
7659480.0
13956768.0
17696040.0
13956768.0
10084840.0
17696040.0
12499520.0
17696040.0
9374640.0
17696040.0
419760.0
17696040.0
388080.0
17